import React from "react";
import "./Terms.css";
import Navbar from "../Home/Navbar/Navbar";

function Terms() {
    return(
        <>
         <section className="main-section-terms">
                    <div className="first-div-terms">
                        <h1 className="main-heading-terms">Términos y condiciones</h1>
                        <h4 className="subheading-terms">POR FAVOR LEA ESTOS TÉRMINOS Y CONDICIONES DETENIDAMENTE ANTES DE UTILIZAR ESTE SITIO WEB</h4>
                        <h5 className="terms-title">¿Qué hay en estos términos?</h5>
                        <p className="terms-paragraph">Estos términos le informan las reglas para usar nuestro sitio web, www.useonedoor.co (nuestro sitio web).</p>
                        <h5 className="terms-title">Quiénes somos y cómo contactarnos</h5>
                        <p className="terms-paragraph">Nuestro sitio web opera como OneDoor limitada ("Nosotros"). Para contactarnos, envíe un correo electrónico a hola@useonedoor.co</p>
                        <h5 className="terms-title">Al utilizar nuestro sitio web, acepta estos términos</h5>
                        <p className="terms-paragraph">Al utilizar nuestro sitio web, confirma que acepta estos términos de uso y que acepta cumplirlos.</p>
                        <p className="terms-paragraph">Si no está de acuerdo con estos términos, no debe utilizar nuestro sitio web.</p>
                        <h5 className="terms-title">Hay otros términos que pueden aplicarse a usted</h5>
                        <p className="terms-paragraph">Estos términos y condiciones se refieren a los siguientes términos adicionales, que también se aplican a su uso de nuestro sitio web:</p>
                        <p className="terms-paragraph">Nuestra <a href="#">Política de privacidad</a>, que establece los términos en los que procesamos los datos personales que recopilamos de usted o que nos 
                        proporciona. Al utilizar nuestro sitio web, usted da su consentimiento para dicho procesamiento y garantiza que todos los datos proporcionados por usted son precisos.</p>
                        <h5 className="terms-title">Nosotros podriamos</h5>
                        <ol>
                            <li className="terms-paragraph">modificar estos términos de vez en cuando. Cada vez que desee utilizar nuestro sitio web, consulte estos términos para asegurarse de que comprende los términos que se aplican en ese momento.</li>
                            <li className="terms-paragraph">actualizar y cambiar nuestro sitio web de vez en cuando.</li>
                        </ol>
                        <h5 className="terms-title">Podemos suspender o retirar nuestro sitio web</h5>
                        <p className="terms-paragraph">Nuestro sitio web está disponible de forma gratuita.<br></br><br></br>No garantizamos que nuestro sitio web, o cualquier contenido en él, 
                        esté siempre disponible o sin interrupciones. Podemos suspender, retirar o restringir la disponibilidad de todo o parte de nuestro sitio web por razones comerciales y operativas. 
                        Intentaremos darle un aviso razonable de cualquier suspensión o retiro.<br></br><br></br>También es responsable de garantizar que todas las personas que accedan a nuestro sitio web 
                        a través de su conexión a Internet conozcan estos términos de uso y otros términos y condiciones aplicables, y que los cumplan.</p>
                        <h5 className="terms-title">Usuarios de nuestro sitio web</h5>
                        <p className="terms-paragraph">Nuestro sitio web está disponible para personas de todo Latino America. Los visitantes del sitio web deben cumplir con las leyes aplicables del país en el que acceden al sitio web.</p>
                        <h5 className="terms-title">Cómo puede utilizar el material de nuestro sitio web</h5>
                        <p className="terms-paragraph">Somos el propietario o el licenciatario de todos los derechos de propiedad intelectual en nuestro sitio web y en el material publicado en él. 
                        Esas obras están protegidas por leyes y tratados de derechos de autor en todo el mundo. Todos los derechos están reservados.<br></br><br></br>Puede imprimir una copia y descargar 
                        extractos de cualquier página de nuestro sitio web para su uso personal y puede llamar la atención de otras personas dentro de su organización sobre el contenido publicado en nuestro 
                        sitio web.<br></br><br></br>No debe modificar las copias en papel o digitales de ningún material que haya impreso o descargado de ninguna manera, y no debe utilizar ilustraciones, 
                        fotografías, secuencias de video o audio o gráficos por separado del texto que lo acompaña.<br></br><br></br>Siempre se debe reconocer nuestro estado (y el de cualquier contribuyente identificado) 
                        como autores del contenido de nuestro sitio web.<br></br><br></br>No debe utilizar ninguna parte del contenido de nuestro sitio web con fines comerciales sin obtener una licencia para hacerlo de 
                        nosotros o de nuestros licenciantes.<br></br><br></br>Si imprime, copia o descarga cualquier parte de nuestro sitio web en violación de estos términos de uso, su derecho a utilizar nuestro sitio 
                        web cesará inmediatamente y deberá, a nuestra discreción, devolver o destruir cualquier copia de los materiales que haya realizado.</p>
                        <h5 className="terms-title">No confíe en la información de este sitio web</h5>
                        <p className="terms-paragraph">El contenido de nuestro sitio web se proporciona solo para información general. No pretende ser un consejo en el que deba confiar. Debe obtener asesoramiento 
                        profesional o especializado antes de emprender o abstenerse de cualquier acción basada en el contenido de nuestro sitio web.<br></br><br></br>Aunque hacemos esfuerzos razonables para actualizar 
                        la información en nuestro sitio web, no hacemos declaraciones, garantías, ya sean expresas o implícitas, de que el contenido de nuestro sitio web sea exacto, completo o actualizado.</p>
                        <h5 className="terms-title">No somos responsables de los sitios web a los que enlazamos</h5>
                        <p className="terms-paragraph">Cuando nuestro sitio web contiene enlaces a otros sitios web y recursos proporcionados por terceros, estos enlaces se proporcionan solo para su información. 
                        Dichos enlaces no deben interpretarse como una aprobación por nuestra parte de esos sitios web vinculados o la información que pueda obtener de ellos.<br></br><br></br>No tenemos control sobre el contenido de esos sitios web o recursos.</p>
                        <h5 className="terms-title">El contenido generado por el usuario no está aprobado por nosotros.</h5>
                        <p className="terms-paragraph">Este sitio web puede incluir información y materiales subidos por otros usuarios del sitio web, incluyendo tableros de anuncios y salas de chat. 
                        Esta información y estos materiales no han sido verificados ni aprobados por nosotros. Las opiniones expresadas por otros usuarios en nuestro sitio web no representan nuestras opiniones o valores.</p>
                        <h5 className="terms-title">Nuestra responsabilidad por las pérdidas o daños sufridos por usted</h5>
                        <ul>
                            <li className="terms-paragraph">No excluimos ni limitamos de ninguna manera nuestra responsabilidad hacia usted cuando sea ilegal hacerlo. Esto incluye responsabilidad por muerte o lesiones 
                            personales causadas por nuestra negligencia o la negligencia de nuestros empleados, agentes o subcontratistas y por fraude o tergiversación fraudulenta.</li>
                            <li className="terms-paragraph">Excluimos todas las condiciones implícitas, garantías, representaciones u otros términos que puedan aplicarse a nuestro sitio web o cualquier contenido en él.</li>
                            <li className="terms-paragraph">No seremos responsables ante usted por ninguna pérdida o daño, ya sea por contrato, agravio (incluida la negligencia), incumplimiento de la obligación legal o de otro modo, incluso si es previsible, que surja de o en conexión con:
                            <ul>
                                <li className="terms-paragraph">uso o imposibilidad de usar nuestro sitio web; o</li>
                                <li className="terms-paragraph">uso o dependencia de cualquier contenido mostrado en nuestro sitio web.</li>
                            </ul></li>
                            <li className="terms-paragraph">En particular, no seremos responsables de:
                            <ul>
                                <li className="terms-paragraph">pérdida de ganancias, ventas, negocios o ingresos;</li>
                                <li className="terms-paragraph">interrupción del negocio;</li>
                                <li className="terms-paragraph">pérdida de ahorros anticipados;</li>
                                <li className="terms-paragraph">pérdida de oportunidades comerciales, buena voluntad o reputación; o</li>
                                <li className="terms-paragraph">cualquier pérdida o daño indirecto o consecuente.</li>
                            </ul></li>
                        </ul>
                        <h5 className="terms-title">No somos responsables de los virus y no debes introducirlos.</h5>
                        <p className="terms-paragraph">No garantizamos que nuestro sitio web sea seguro o esté libre de errores o virus.
                        <br></br><br></br>Usted es responsable de configurar la tecnología, los programas informáticos y la plataforma para acceder a nuestro sitio web. Debe utilizar su propio software de protección antivirus.<br></br><br></br>
                        No debe hacer un mal uso de nuestro sitio web introduciendo a sabiendas virus, troyanos, gusanos, bombas lógicas u otro material que sea malicioso o tecnológicamente dañino. No debe intentar obtener acceso no autorizado 
                        a nuestro sitio web, el servidor en el que se almacena nuestro sitio web o cualquier servidor, computadora o base de datos conectada a nuestro sitio web. No debe atacar nuestro sitio web mediante un ataque de denegación 
                        de servicio o un ataque de denegación de servicio distribuido. Al infringir esta disposición, cometería un delito en virtud de la Ley de uso indebido de computadoras de 1990. Informaremos de dicha infracción a las autoridades 
                        policiales pertinentes y cooperaremos con esas autoridades revelándoles su identidad. En caso de tal incumplimiento, su derecho a utilizar nuestro sitio web cesará de inmediato.</p>
                        <h5 className="terms-title">Reglas sobre la vinculación a nuestro sitio web</h5>
                        <p className="terms-paragraph">Puede vincular a nuestra página de inicio, siempre que lo haga de una manera que sea justa y legal y no dañe nuestra reputación ni se aproveche de ella.<br></br><br></br>No debe establecer 
                        un enlace de manera que sugiera cualquier forma de asociación, aprobación o respaldo de nuestra parte donde no exista.<br></br><br></br>No debe establecer un enlace a nuestro sitio web en ningún sitio web que no sea de su propiedad.<br></br><br></br>
                        Nuestro sitio web no debe estar enmarcado en ningún otro sitio web, ni puede crear un enlace a ninguna parte de nuestro sitio web que no sea la página de inicio.<br></br><br></br>Nos reservamos el derecho de retirar el permiso de vinculación sin previo aviso.</p>
                        <h5 className="terms-title">¿Las leyes de qué país se aplican a cualquier disputa?</h5>
                        <p className="terms-paragraph">Si es un consumidor, tenga en cuenta que estos términos de uso, su contenido y su formación se rigen por la ley Colombiana. Usted y nosotros estamos de acuerdo en que los tribunales de Colombia tendrán jurisdicción exclusiva.<br></br><br></br>
                        Si usted es una empresa, estos términos de uso, su objeto y su formación (y cualquier disputa o reclamo no contractual) se rigen por la ley Colombiana. Ambos aceptamos la jurisdicción exclusiva de los tribunales de Colombia.</p>
                        <h5 className="terms-title">OneDoor, 2021</h5>
                        <h4 className="subheading-terms">ONEDOOR: TÉRMINOS Y CONDICIONES DE AUTOSERVICIO: (XXXXX)</h4>
                        <p className="terms-paragraph">Al descargar la aplicación de oneDoor a través de su cuenta de XXXXXX, (como se define a continuación), usted ("Cliente") acepta regirse por los siguientes términos y condiciones ("Términos y condiciones").</p>
                        <h5 className="terms-title">1. Definiciones e interpretación</h5>
                        <p className="terms-paragraph">Estas definiciones se aplicarán en estos Términos y Condiciones.</p>
                        <ul>
                            <li className="terms-paragraph"><span className="terms-span">"Datos del cliente"</span> se refiere a todos los datos, información y material de entrada o cargados en la aplicación de OneDoor</li>
                            <li className="terms-paragraph"><span className="terms-span">“Materiales del Cliente”</span> significa cualquier material propiedad del Cliente que es proporcionado o puesto a disposición por o en nombre del Cliente a OneDoor con 
                            el propósito de incorporarlo a la Aplicación de OneDoor para el Cliente u otro uso permitido por OneDoor pero excluyendo los Datos del Cliente.</li>
                            <li className="terms-paragraph"><span className="terms-span">"Fecha de vigencia"</span> significa la fecha en la que descarga y comienza a usar la aplicación de OneDoor a través de su cuenta de XXXXX.</li>
                            <li className="terms-paragraph"><span className="terms-span">“Política de uso justo”</span> significa, con respecto al Catálogo y Contactos, XXXXX mensajes enviados o recibidos por mes.</li>
                            <li className="terms-paragraph"><span className="terms-span">“Tarifas”</span> se refiere a las tarifas por el uso de la aplicación de OneDoor como se muestra en la tienda de aplicaciones de XXXXX.</li>
                            <li className="terms-paragraph"><span className="terms-span">"Derechos de propiedad intelectual"</span> significa patentes, derechos patentables, derechos de autor, derechos de diseño, modelos de utilidad, 
                            marcas comerciales (estén o no registradas), nombres comerciales, derechos sobre nombres de dominio, derechos sobre invenciones, derechos sobre datos, derechos debase de datos, derechos de "saber como" e información confidencial, y 
                            todos los demás derechos de propiedad intelectual e industrial y derechos similares o análogos que existan bajo las leyes de cualquier país y todas las solicitudes pendientes y derecho a solicitar o registrar los mismos 
                            (presentes, futuros y contingentes). , e incluyendo todas las renovaciones, extensiones, reactivaciones y todos los derechos de acción acumulados).</li>
                            <li className="terms-paragraph"><span className="terms-span">"Aplicación de OneDoor"</span> hace referencia a cualquier aplicación patentada que se descargue a través de la tienda de aplicaciones de XXXXX.</li>
                            <li className="terms-paragraph"><span className="terms-span">"Contenido de OneDoor"</span> significa todos los datos, información y material propiedad de OneDoor o con licencia de OneDoor y que se incluyen 
                            dentro de la Aplicación de OneDoor, pero excluyendo los Datos del Cliente y los Materiales del Cliente.</li>
                            <li className="terms-paragraph"><span className="terms-span">"Cuenta de XXXXX"</span> significa la cuenta que tiene con XXXXX.Com.</li>
                            <li className="terms-paragraph"><span className="terms-span">“Tienda de aplicaciones de XXXXX”</span> significa la tienda de aplicaciones proporcionada por XXXXXX.Com.</li>
                            <li className="terms-paragraph"><span className="terms-span">“Software”</span> significa cualquier software propiedad de OneDoor o con licencia de OneDoor y que forma parte de, o se utiliza en la provisión de, cualquier Producto o Servicio.</li>
                        </ul>
                        <h5 className="terms-title">2. Servicios</h5>
                        <p className="terms-paragraph">2.1 Sujeto al pago total de las Tarifas aplicables y sujeto a las otras disposiciones de estos Términos y Condiciones, al Cliente se le otorga una licencia limitada, no exclusiva e intransferible para acceder 
                        y utilizar la Aplicación de OneDoor de acuerdo con cualquier otra restricción establecida en este documento y durante el período que tenga una Cuenta de XXXXX y continúe pagando las Tarifas. El Cliente no puede sublicenciar el derecho de 
                        acceso y / o uso de la Aplicación De OneDoor a ningún tercero. Salvo que se establezca expresamente en estos Términos y condiciones, todos los derechos sobre la Aplicación de OneDoor (incluido el Contenido Hero pero excluyendo los Datos del 
                        cliente y los Materiales del cliente) y el Software están reservados para OneDoor.</p>
                        <p className="terms-paragraph">2.2 El Cliente deberá cumplir con todos los términos de uso (incluidas, cuando corresponda, las políticas de privacidad y / o cookies) que OneDoor pueda publicar en línea a través del Servicio, cada uno de ellos 
                        actualizado por OneDoor de vez en cuando, todos los cuales se incorporan a estos Términos y condiciones por referencia.</p>
                        <p className="terms-paragraph">2.3 El Cliente no deberá: (a) excepto según lo expresamente permitido por estos Términos y Condiciones, permitir que un tercero acceda o use cualquier Producto o Servicio o lo use en nombre de un tercero 
                        (lo que incluye operar cualquier forma de instalación en nombre de cualquier tercero u operando una oficina de software o servicio similar); (b) copiar, traducir, modificar, adaptar o crear trabajos derivados de cualquier Producto o Servicio; 
                        (c) “enmarcar” o “reflejar” cualquier Contenido de OneDoor en cualquier otro servidor o dispositivo inalámbrico o basado en Internet; (d) intentar descubrir u obtener acceso al código fuente del Software o realizar ingeniería inversa, modificar, 
                        descifrar, extraer, desensamblar o descompilar el Software (excepto estrictamente en la medida en que el Cliente esté autorizado a hacerlo según la ley aplicable en las circunstancias) bajo el cual OneDoor no tiene el derecho legal de restringir o 
                        prevenir lo mismo), incluso para: (i) construir un producto o servicio competitivo; (ii) crear un producto utilizando ideas, características, funciones o gráficos similares de la aplicación de OneDoor; (iii) copiar cualquier idea, característica, 
                        función o gráfico de la aplicación de OneDoor; (e) cargar, almacenar, publicar, enviar por correo electrónico, transmitir o poner a disposición de cualquier otro modo cualquier contenido que infrinja los Derechos de propiedad intelectual o la protección 
                        de datos, la privacidad u otros derechos de cualquier otra persona, sea difamatorio o infrinja cualquier deber contractual o cualquier obligación de confidencial, es obsceno, sexualmente explícito, amenazante, incita a la violencia o al odio, blasfemo, 
                        discriminatorio (por cualquier motivo), deliberadamente falso o engañoso, o que no cumple con todas las leyes y regulaciones aplicables o es objetable o prohibido según lo establecido en cualquier política de uso aceptable publicada en línea a través del 
                        Servicio, actualizada por OneDoor de vez en cuando (<span className="terms-span">"Contenido prohibido"</span>).</p>
                        <p className="terms-paragraph">2.4 El Cliente será responsable de todo acceso y uso de la Aplicación de OneDoor. El Cliente reconoce y acepta que será el único responsable de todas las actividades realizadas a través de la Aplicación de OneDoor. 
                        El Cliente notificará de inmediato a OneDoor cuando tenga conocimiento de cualquier acceso o uso no autorizado de la Aplicación de OneDoor y proporcionará toda la asistencia razonable a OneDoor para poner fin a dicho acceso o uso no autorizado.</p>
                        <p className="terms-paragraph">2.5 El Cliente comprende que la Aplicación de OneDoor y / o el Software pueden incluir componentes de seguridad que permitan proteger los materiales digitales y que el uso de estos materiales está sujeto a los 
                        proveedores de contenido que proporcionan contenido a la Aplicación de OneDoor. El Cliente no puede intentar anular o eludir ninguna de las reglas de uso integradas en el Servicio. Queda estrictamente prohibida cualquier reproducción, 
                        publicación, posterior distribución o exhibición pública no autorizada del Contenido de OneDoor, en su totalidad o en parte.</p>
                        <h5 className="terms-title">3. Servicios de apoyo</h5>
                        <p className="terms-paragraph">3.1 OneDoor solo proporcionará soporte por correo electrónico. OneDoor emitirá modificaciones del Software cuando corresponda mediante una corrección o parche local del Software u otra solución adecuada a la absoluta 
                        discreción de OneDoor. OneDoor no cobrará por las actualizaciones; sin embargo, OneDoor se reserva el derecho de cobrar por cualquier lanzamiento nuevo y / o versión nueva con respecto al Software.</p>
                        <p className="terms-paragraph">3.2 OneDoor no estará obligado a respaldar el Software si el Cliente no mantiene el Software en el nivel de lanzamiento especificado por OneDoor, a menos que las Partes acuerden lo contrario por escrito.</p>
                        <p className="terms-paragraph">3.3 OneDoor no tendrá la obligación de brindar soporte cuando surjan fallas por el uso indebido o incorrecto del Software, el uso del Software en combinación con equipo o software no designado por OneDoor 
                        para su uso con el Software, la reubicación o instalación del Software por cualquier otra persona que OneDoor, error del operador y / o de otro modo con una justificación razonable de OneDoor.</p>
                        <p className="terms-paragraph">3.4 El Cliente no podrá utilizar una empresa alternativa para respaldar y / o mantener el Software.</p>
                        <h5 className="terms-title">4. Garantías de OneDoor</h5>
                        <p className="terms-paragraph">4.1 OneDoor garantiza que: (i) actuará con el debido cuidado y seguirá los más altos estándares profesionales en la provisión de la aplicación de OneDoor; (ii) proporcionará la aplicación de OneDoor de acuerdo 
                        con todas las leyes y regulaciones aplicables (incluidas, entre otras, las leyes de protección de datos); (iii) el uso de la aplicación de OneDoor no infringirá ni violará ningún derecho de autor, secreto comercial, licencias u otros derechos de propiedad de terceros.</p>
                        <p className="terms-paragraph">4.2 OneDoor hará todos los esfuerzos comercialmente razonables para que la aplicación de OneDoor esté disponible, excepto para: (i) mantenimiento planificado y (ii) mantenimiento no programado realizado fuera del horario comercial normal. 
                        OneDoor no garantiza que: (i) el uso de la Aplicación de OneDoor por parte del Cliente sea ininterrumpido o sin errores o (ii) que la información obtenida por el Cliente a través de la Aplicación de OneDoor cumpla con los requisitos del Cliente.</p>
                        <h5 className="terms-title">5. Garantías del cliente</h5>
                        <p className="terms-paragraph">El Cliente garantiza que (i) proporcionará a OneDoor toda la cooperación necesaria y el acceso a toda la información necesaria que OneDoor pueda requerir razonablemente para proporcionar la Aplicación de OneDoor; (ii) no acceder, almacenar, 
                        distribuir o transmitir ningún virus; (iii) asegurarse siempre de que su uso del Servicio está de acuerdo con las leyes y regulaciones aplicables (incluidas, entre otras, las Leyes de Protección de Datos); (iv) obtener los consentimientos necesarios para su uso del Servicio; 
                        (v) no intentar copiar, modificar, duplicar, crear trabajos derivados, enmarcar, duplicar, volver a publicar, descargar, mostrar, transmitir o distribuir todo o parte del Servicio en cualquier forma o medio o por cualquier medio o intento de compilar, desensamblar, realizar ingeniería inversa 
                        o reducir de otro modo a una forma perceptible por humanos todo o parte del Servicio.</p>
                        <h5 className="terms-title">6. Tarifas y facturación</h5>
                        <p className="terms-paragraph">6.1 La relación de facturación de conformidad con estos Términos y condiciones será manejada por XXXXXX. El Cliente pagará las Tarifas a XXXXXX de forma mensual y periódica y de acuerdo con los términos de pago de XXXXX.</p>
                        <p className="terms-paragraph">6.2 Independientemente de dónde se encuentre el Cliente, las tarifas por los Servicios siempre se cobrarán en dólares estadounidenses.</p>
                        <p className="terms-paragraph">6.3 A menos que se disponga expresamente lo contrario en estos Términos y condiciones, todos los montos a los que se hace referencia en estos Términos y condiciones son exclusivos del impuesto al valor agregado (IVA) 
                        u otro impuesto a las ventas aplicable que, cuando sea cobrado por OneDoor, será pagadero por el Cliente a la tasa y en la forma prescrita por la ley.</p>
                        <h5 className="terms-title">7. Protección de datos</h5>
                        <p className="terms-paragraph">7.1 Leyes de protección de datos significa leyes aplicables relacionadas con: (i) protección de datos; (ii) privacidad; y (iii) restricciones o requisitos con respecto al procesamiento de datos personales de cualquier tipo, 
                        incluido el Reglamento General de Protección de Datos de la UE 2016/679, (<span className="terms-span">"GDPR"</span>). “Controlador de datos”, Procesador de datos ”,“ Sujeto de datos ”, Datos personales” y “Procesamiento” tendrán los mismos significados que en las Leyes de protección 
                        de datos y se interpretarán en consecuencia. Ninguna de las Partes hará nada que pueda causar que la otra Parte incumpla sus obligaciones bajo las Leyes de Protección de Datos. El Cliente es el Controlador a los efectos de estos Términos y Condiciones y el uso de la Aplicación de OneDoor 
                        por parte de los Clientes estará sujeto a la política de privacidad del Cliente. OneDoor solo procesará los Datos personales para los fines que le notifique el Cliente y cumplirá con todas las instrucciones para garantizar el cumplimiento de las Leyes de protección de datos. 
                        OneDoor no transferirá, sin el consentimiento previo por escrito del Cliente, dichos datos a un país o territorio fuera del pais de origen, a menos que primero se hayan establecido garantías contractuales u otras garantías adecuadas que permitan a cada Parte cumplir con los 
                        requisitos de las Leyes de Protección de Datos.</p>
                        <p className="terms-paragraph">7.2 OneDoor deberá: (a) cumplir y cumplir con sus obligaciones bajo las Leyes de Protección de Datos y sus obligaciones con respecto al procesamiento de Datos Personales bajo estos Términos y Condiciones y en particular, sin limitación, donde las Leyes de 
                        Protección de Datos incluyen el RGPD, las obligaciones a las que se hace referencia en el artículo 28 del RGPD; (b) procesar los Datos personales solo en nombre del Cliente, solo con el fin de cumplir con estos Términos y condiciones y solo de acuerdo con las instrucciones documentadas 
                        contenidas en estos Términos y condiciones o recibidas del Cliente de vez en cuando; (c) no modificar, enmendar o alterar de otra manera el contenido de los Datos Personales o divulgar o permitir la divulgación de cualquiera de los Datos Personales a terceros a menos que el Cliente lo 
                        autorice específicamente por escrito; (d) implementar las medidas técnicas y organizativas adecuadas para proteger los Datos personales contra el procesamiento no autorizado o ilegal y contra la pérdida, destrucción, daño, alteración o divulgación accidentales. 
                        Si el Cliente lo solicita, OneDoor proporcionará una descripción por escrito de los métodos técnicos y organizativos empleados por OneDoor para procesar los Datos personales (dentro de los plazos razonablemente requeridos por el Cliente); (e) proporcionar asistencia razonable al Cliente 
                        para garantizar el cumplimiento con respecto a la seguridad de los Datos personales y las evaluaciones de impacto de la protección de datos y las consultas previas. Cuando las leyes de protección de datos incluyan el RGPD, esto incluirá todas las disposiciones de los artículos 32 a 34 
                        (ambos inclusive) del RGPD; (f) ayudar al Cliente en la medida de lo posible a cumplir con sus obligaciones con los interesados ​​en relación con los derechos de dichos interesados. Cuando las Leyes de Protección de Datos incluyan el RGPD, esto incluirá todos los derechos de acceso del 
                        interesado en el Capítulo III del RGPD; (g) no publicar, divulgar o divulgar ninguno de los Datos personales a ningún tercero, incluido, para evitar dudas, el propio interesado, a menos que el Cliente lo indique por escrito; (h) tomar medidas razonables para garantizar la confiabilidad 
                        de cualquier miembro del personal del Cliente que tenga acceso a los Datos Personales; (i) garantizar que solo aquellos miembros del personal del Cliente que necesitan tener acceso a los Datos personales tengan acceso a dichos Datos personales y solo para los fines del cumplimiento de 
                        estos Términos y condiciones y todo el personal del Cliente requerido para acceder a los Los Datos Personales son informados de la naturaleza confidencial de los Datos Personales, tienen una obligación contractual y / o legal de mantener la confidencialidad de dichos Datos Personales; 
                        (j) de inmediato y sin demora (pero en cualquier caso dentro de las 24 horas posteriores a su conocimiento) notificará al Cliente por escrito de cualquier divulgación no autorizada, pérdida, destrucción, compromiso, daño, alteración o robo de Datos personales (incluido el acceso no autorizado 
                        o uso de los sistemas o datos del Cliente, manejo o eliminación inadecuados de datos, robo de activos de información o tecnología y / o la divulgación involuntaria o intencional de Datos personales) o, cuando las Leyes de protección de datos incluyen el GDPR, cualquier incidente o conjunto 
                        de eventos que puedan dar lugar a una violación de datos personales (tal como se define dicho término en el RGPD); (k) sin demora (teniendo en cuenta las obligaciones del controlador de datos especificadas en las Leyes de protección de datos, incluidos los plazos pertinentes) remitir al Cliente 
                        cualquier solicitud, aviso u otra comunicación de los interesados, la autoridad reguladora en la jurisdicción local pertinente o cualquier otra autoridad encargada de hacer cumplir la ley; (l) a elección del Cliente, eliminar o devolver todos los Datos personales al Cliente en el momento de la 
                        rescisión o expiración de los Términos y condiciones y eliminar cualquier copia existente de dichos Datos personales, a menos que las leyes aplicables exijan que OneDoor retenga los Datos personales, en cuyo caso, solo dichos Datos Personales podrán retenerse estrictamente con el fin de cumplir 
                        con las leyes aplicables; y (m) OneDoor hará una copia de seguridad periódica de los datos del cliente, OneDoor los conservará durante la vigencia de los Términos y condiciones y se devolverán al cliente si así lo solicita. Todos los datos del cliente se anonimizarán cuando se almacenen en los 
                        servidores de OneDoor; (n) Cualquier dato del cliente en poder de OneDoor en la fecha de terminación de estos Términos y condiciones deberá, previa solicitud por escrito, ser transferido al Cliente o, a petición exclusiva del Cliente, eliminado, dentro de los 30 días posteriores a dicha terminación 
                        o según lo acordado entre las fiestas.</p>
                        <h5 className="terms-title">8. Confidencialidad</h5>
                        <p className="terms-paragraph">Cada Parte reconoce que ella o sus empleados pueden, en el curso del desempeño de sus responsabilidades bajo estos Términos y Condiciones, estar expuestos o adquirir información que sea de propiedad o confidencial de esa Parte o sus compañías afiliadas o sus clientes o 
                        terceros para a quien esa Parte tiene el deber de confidencialidad. Toda la información no pública de cualquier forma obtenida por una de las Partes o sus empleados mientras proporciona o recibe la aplicación de OneDoor se considerará Información confidencial y patentada. Cada Parte acuerda mantener 
                        dicha información en estricta confidencialidad y no copiar, grabar, reproducir (usando cualquier medio), vender, ceder, licenciar, comercializar, transferir o de otra manera disponer, dar o divulgar dicha información a terceros o usarla. información para cualquier propósito que no sea la provisión de 
                        la aplicacion de OneDoor al Cliente y para informar a cada uno de sus empleados que puedan estar expuestos a dicha Información confidencial y patentada de sus obligaciones de mantener dicha información confidencial.</p>
                        <h5 className="terms-title">9. Propiedad intelectual</h5>
                        <p className="terms-paragraph">9.1 Nada en estos Términos y Condiciones causará que la propiedad de los Derechos de Propiedad Intelectual pertenecientes a una Parte sea transferida a la otra.</p>
                        <p className="terms-paragraph">9.2 OneDoor y / o sus licenciantes seguirán siendo, entre las Partes, el propietario de todos los derechos de propiedad intelectual sobre las marcas, marcas comerciales y logotipos de OneDoor, el Producto (s), el Servicio (incluido el Contenido de OneDoor pero excluyendo 
                        los Datos y los Materiales del Cliente). ) y el Software. Salvo lo expresamente permitido por estos Términos y condiciones, el Cliente no puede utilizar ninguno de los Derechos de propiedad intelectual de OneDoor sin el consentimiento previo por escrito de OneDoor.</p>
                        <p className="terms-paragraph">9.3 El Cliente reconoce que puede crear Derechos de Propiedad Intelectual mejorando o sugiriendo mejoras del Software a OneDoor. Todas y cada una de las mejoras al Software o la Aplicación de OneDoor desarrolladas por el Cliente que resulten en la creación de Derechos de 
                        Propiedad Intelectual serán propiedad de OneDoor. Por la presente, el Cliente cede todos y cada uno de los derechos sobre dichos Derechos de propiedad intelectual con respecto al Software o la Aplicación de OneDoor a OneDoor y renuncia a sus derechos morales con respecto a los mismos.</p>
                        <p className="terms-paragraph">9.4 Cada Parte llamará la atención de la otra de inmediato sobre cualquier uso indebido o indebido de los Derechos de Propiedad Intelectual de la otra Parte que lleguen a su conocimiento.</p>
                        <p className="terms-paragraph">9.5 El Cliente y / o sus licenciantes seguirán siendo, entre las Partes, el propietario de todos los Derechos de propiedad intelectual, incluidos, entre otros, los Datos del cliente, las marcas comerciales y los logotipos y los Materiales del cliente. El Cliente otorga a OneDoor, 
                        sin cargo, una licencia mundial, gratuita y no exclusiva para usar los Datos del Cliente y los Materiales del Cliente solo en la medida necesaria para que OneDoor pueda proporcionar el Servicio al Cliente y cumplir con sus obligaciones. bajo estos Términos y Condiciones. El Cliente garantiza que posee los Datos 
                        del Cliente y los Materiales del Cliente y / o tiene derecho a otorgar la licencia anterior. Si se rescinden estos Términos y condiciones, la licencia anterior terminará.</p>
                        <p className="terms-paragraph">9.6 El Cliente reconoce que OneDoor no tiene control sobre los Datos y Materiales del Cliente alojados como parte de la prestación del Servicio y no supervisa activamente el contenido de los Datos y Materiales del Cliente. OneDoor notificará al Cliente tan pronto como sea 
                        razonablemente posible si tiene conocimiento de cualquier alegación de que los Datos del Cliente y / o los Materiales del Cliente puedan infringir los derechos de terceros (<span className="terms-span">"Material infractor"</span>). En el caso de que OneDoor sospeche razonablemente que los Datos del Cliente o 
                        el Material del Cliente infringen los derechos de terceros, deberá, con notificación previa por escrito al Cliente, eliminar los Datos del Cliente y / o los Materiales del Cliente del Servicio.</p>
                        <p className="terms-paragraph">9.7 OneDoor reconoce y acepta que la propiedad de todos los derechos sobre los Derechos de propiedad intelectual del Cliente en todo momento será conferida y pertenecerá al Cliente y que el uso se acumula para el beneficio exclusivo del Cliente. OneDoor no hará ni causará ni permitirá 
                        que se haga nada a sabiendas que pueda poner en peligro los derechos del Cliente y la propiedad de los Derechos de propiedad intelectual del Cliente.</p>
                        <p className="terms-paragraph">9.8 Sujeto a la Limitación de Responsabilidad a continuación, el Cliente indemnizará a OneDoor contra todos los daños y costos legales finalmente otorgados contra OneDoor por un tribunal de jurisdicción competente y / o los montos pagados por OneDoor después de un acuerdo final aprobado 
                        por el Cliente, junto con los los honorarios legales en los que OneDoor haya incurrido razonablemente como resultado del uso por parte del Cliente del Material infractor en el Servicio y el incumplimiento por parte del Cliente o de sus Usuarios autorizados de estos Términos y condiciones y / o el Servicio infringe los 
                        Derechos de propiedad intelectual de cualquier tercero.</p>
                        <h5 className="terms-title">10. Indemnizaciones</h5>
                        <p className="terms-paragraph">10.1 El Cliente indemnizará y mantendrá indemne a OneDoor, sus directores o empleados, contra todas y cada una de las acciones, reclamaciones, costos, gastos, daños, multas, sanciones y cualquier otra responsabilidad (incluidos los honorarios legales razonables) que surjan de o en relación con: 
                        (a) un incumplimiento de las obligaciones del Cliente en virtud de las leyes de protección de datos; (ii) el uso de la aplicación OneDoor por parte del cliente.</p>
                        <p className="terms-paragraph">10.2 Esta indemnización está sujeta a que la Parte indemnizada notifique sin demora a la Parte indemnizadora de dicha reclamación, permitiendo que la Parte indemnizadora lleve a cabo exclusivamente la defensa, negociación o acuerdo y proporcione toda la cooperación razonable en relación con cualquier reclamación.</p>
                        <h5 className="terms-title">11. Limitación de responsabilidad</h5>
                        <p className="terms-paragraph">11.1 OneDoor no será responsable, ya sea por contrato, agravio (incluida la negligencia), incumplimiento del deber legal, bajo cualquier indemnización o de otro modo, por cualquier pérdida, daño, gasto o responsabilidad incurrida o sostenida como resultado de: (a) el uso de la Aplicación de OneDoor excepto para su 
                        propósito normal previsto, (b) cualquier adaptación o modificación de la Aplicación de OneDoor, o integración o combinación con cualquier otro equipo, software, producto o material no suministrado por OneDoor, en cada caso realizada por otra persona que OneDoor o sin el consentimiento expreso por escrito de OneDoor; (c) cualquier defecto que surja 
                        en cualquier Producto como resultado de un mal uso, daño intencional, negligencia por parte de cualquier otra persona que no sea OneDoor, o cualquier falla por parte del Cliente para seguir las instrucciones de OneDoor en cuanto al uso (según lo provisto por OneDoor y aprobado por escrito por parte del Cliente); (d) cualquier dato del cliente y / o 
                        material del cliente; o (e) el uso continuo de una versión o lanzamiento de la Aplicación de OneDoor después de que OneDoor haya puesto a disposición del Cliente una versión alternativa o el lanzamiento de la Aplicación de OneDoor, en la medida en que cualquier reclamo con respecto a la cual Hero estaría obligado de otro modo, en virtud de estos 
                        Términos y condiciones, se habría evitado indemnizar mediante el uso de dicha versión o lanzamiento alternativo.</p>
                        <p className="terms-paragraph">11.2 En la medida permitida por la ley, OneDoor no tendrá ninguna responsabilidad ante el Cliente en relación con los Términos y condiciones (y para evitar dudas, incluida cualquier responsabilidad de indemnización) por cualquier pérdida y daño indirecto, económico o consecuente y (ii) el La responsabilidad total de 
                        OneDoor en relación con los Términos y condiciones por pérdidas y daños directos, ya sea que surjan por agravio (incluidas negligencia y responsabilidad estricta), contrato o de otro modo, no excederá de $20,000,000.00.</p>
                        <p className="terms-paragraph">11.3 No obstante lo anterior, no se aplicará ninguna limitación, exclusión o restricción de responsabilidad en virtud de estos Términos y condiciones a cualquier responsabilidad que surja de la negligencia, fraude, tergiversación o incumplimiento intencional de cualquiera de las Partes.</p>
                        <h5 className="terms-title">12. Término y rescisión</h5>
                        <p className="terms-paragraph">12.1 Estos Términos y condiciones comenzarán en la Fecha de vigencia y, a menos que se rescindan antes de acuerdo con sus términos, continuarán de conformidad con los Términos de servicio de XXXXX en relación con la rescisión.</p>
                        <p className="terms-paragraph">12.2 Cualquiera de las Partes puede rescindir estos Términos y Condiciones, en cualquier momento, notificando por escrito a la otra parte si la otra: (a) incumple sustancialmente cualquier término de estos Términos y Condiciones y no es posible remediar ese incumplimiento; (b) incumple sustancialmente cualquier 
                        término de estos Términos y condiciones y es posible remediar ese incumplimiento, pero el otro no lo hace dentro de los 14 días posteriores a la solicitud por escrito de hacerlo; o (c) se declare insolvente, se concilie con sus acreedores, tenga un síndico o administrador de su empresa o la totalidad o una parte sustancial de sus bienes designados, 
                        o se dicte una orden, o se apruebe una resolución efectiva, para su administración, Sindicatura, liquidación, liquidación u otro proceso similar, o tiene cualquier angustia, ejecución u otro proceso impuesto o aplicado contra la totalidad o una parte sustancial de sus activos (que no se descarga, paga, retira o elimina dentro de los 28 días) , 
                        o está sujeto a cualquier procedimiento que sea equivalente o sustancialmente similar a cualquiera de los anteriores bajo cualquier jurisdicción aplicable, o deja de comerciar o amenaza con hacerlo.</p>
                        <p className="terms-paragraph">12.3 Sin perjuicio de lo anterior, OneDoor puede, además, y sin responsabilidad, rescindir estos Términos y condiciones o, alternativamente, puede suspender el acceso y el uso de la Aplicación de OneDoor cuando el Cliente deje de pagar las Tarifas. Además, sin responsabilidad, OneDoor puede rescindir inmediatamente 
                        estos Términos y condiciones en caso de que el Cliente cancele su Cuenta de XXXXX.</p>
                        <p className="terms-paragraph">12.4 Ambas Partes pueden además, y sin responsabilidad, rescindir estos Términos y Condiciones, o alternativamente, notificando por escrito a la otra Parte si la Parte infractora está en incumplimiento persistente o reiterado de cualquiera de sus obligaciones en virtud de estos Términos y Condiciones 
                        (ya sea o no es la misma obligación que se incumple y se subsanan o no dichos incumplimientos).</p>
                        <p className="terms-paragraph">12.5 En relación con las suspensiones en virtud de la cláusula 12.3, el acceso al Servicio se restablecerá inmediatamente después de que OneDoor reciba el pago total y los fondos compensados.</p>
                        <p className="terms-paragraph">12.6 Las tarifas seguirán siendo pagaderas durante cualquier período de suspensión, a pesar de que el Cliente o algunos de los Usuarios autorizados pueden no tener acceso al Servicio.</p>
                        <h5 className="terms-title">13. Consecuencias de la rescisión</h5>
                        <p className="terms-paragraph">Tras la terminación de estos Términos y condiciones por cualquier motivo: (a) el Cliente dejará inmediatamente de acceder y descontinuará todo uso de la Aplicación de OneDoor; (b) todos los montos pagaderos a OneDoor por el Cliente serán inmediatamente pagaderos y adeudados; (c) Las tarifas solo se pagarán hasta 
                        el momento de la rescisión, sin embargo, cuando las tarifas se paguen por adelantado, no habrá ningún reembolso.</p>
                        <h5 className="terms-title">14. General</h5>
                        <p className="terms-paragraph">14.1 Estos Términos y Condiciones no confieren ningún derecho a ninguna persona o parte (que no sean las Partes de estos Términos y Condiciones y, cuando corresponda, sus sucesores y cesionarios permitidos) de conformidad con la Ley de Contratos (Derechos de Terceros) de 1999.</p>
                        <p className="terms-paragraph">14.2 Cualquier notificación enviada a una Parte en virtud o en relación con estos Términos y Condiciones deberá ser por escrito y deberá: a) entregarse en mano o por correo de primera clase prepago u otro servicio de entrega al día hábil siguiente en su domicilio social ( si es una empresa) o su lugar 
                        principal de negocios (en cualquier otro caso); o b) enviado por correo electrónico a [].</p>
                        <p className="terms-paragraph">14.3 Cualquier notificación se considerará recibida: a) si se entrega en mano, con la firma de un recibo de entrega o en el momento en que la notificación se deja en la dirección correspondiente; y b) si se envía por correo de primera clase prepago u otro servicio de entrega al siguiente día hábil, a las 9.00 horas 
                        del segundo Día Hábil posterior al envío o a la hora registrada por el servicio de entrega.</p>
                        <p className="terms-paragraph">14.4 Las Cláusulas 14.2 y 14.3 no se aplican al servicio de cualquier procedimiento u otros documentos en cualquier acción legal o, cuando corresponda, cualquier arbitraje u otro método de resolución de disputas.</p>
                        <p className="terms-paragraph">14.5 Estos Términos y Condiciones constituyen la totalidad de los Términos y Condiciones entre las Partes en relación con su tema y reemplaza y reemplaza todos los demás Términos y Condiciones, escritos u orales con respecto a su tema. Cada Parte reconoce que no se basa en ningún compromiso, promesa, aseguramiento, 
                        declaración, representación, garantía o entendimiento (ya sea por escrito o no) de ninguna persona (ya sea parte de estos Términos y Condiciones o no) en relación con el tema de estos Términos y Condiciones que no sean los expresamente establecidos en estos Términos y Condiciones.</p>
                        <p className="terms-paragraph">14.6 Ninguna variación de estos Términos y Condiciones será efectiva a menos que sea por escrito y acordada entre las Partes.</p>
                        <p className="terms-paragraph">14.7 Estos Términos y condiciones y cualquier obligación extracontractual que surja de o en relación con estos Términos y condiciones se regirán en todos los aspectos por la ley inglesa y las Partes acuerdan que los tribunales ingleses tendrán jurisdicción exclusiva para conocer y determinar cualquier demanda, 
                        acción o procedimiento que surja de o en conexión con estos Términos y Condiciones, incluidas las obligaciones extracontractuales que surjan de o en conexión con estos Términos y Condiciones.</p>
                        <h5 className="terms-title">FIN</h5>
                    </div>
                </section>
        </>
    )
}

export default Terms;